-- Fixpack: M0 Audit Trail for paid DevOrders (idempotent)
-- Created by: Архитектор Яцков Евгений Анатольевич
-- Purpose:
--   - Minimal immutable-ish audit trail for monetization readiness
--   - Works even if only dev_order_id exists (dev_task_id optional)
-- Verify:
--   - verify_m0.sql will insert+rollback a test audit event.

BEGIN;

CREATE SCHEMA IF NOT EXISTS ops;

CREATE TABLE IF NOT EXISTS ops.audit_events (
    audit_event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts             TIMESTAMPTZ NOT NULL DEFAULT now(),
    actor          TEXT NOT NULL,
    action         TEXT NOT NULL,
    ok             BOOLEAN NOT NULL DEFAULT FALSE,

    dev_order_id   BIGINT NULL,
    dev_task_id    BIGINT NULL,

    payload        JSONB NOT NULL DEFAULT '{}'::jsonb,
    evidence_refs  JSONB NOT NULL DEFAULT '[]'::jsonb,
    err            TEXT NULL,

    CONSTRAINT audit_events_actor_nonempty  CHECK (btrim(actor) <> ''),
    CONSTRAINT audit_events_action_nonempty CHECK (btrim(action) <> '')
);

-- Indexes (fast lookup by order/task, time)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='ops' AND indexname='audit_events_ts_idx') THEN
        CREATE INDEX audit_events_ts_idx ON ops.audit_events (ts DESC);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='ops' AND indexname='audit_events_order_ts_idx') THEN
        CREATE INDEX audit_events_order_ts_idx ON ops.audit_events (dev_order_id, ts DESC)
        WHERE dev_order_id IS NOT NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='ops' AND indexname='audit_events_task_ts_idx') THEN
        CREATE INDEX audit_events_task_ts_idx ON ops.audit_events (dev_task_id, ts DESC)
        WHERE dev_task_id IS NOT NULL;
    END IF;
END$$;

-- Optional FKs (only if target relations exist)
DO $$
BEGIN
    IF to_regclass('dev.dev_order') IS NOT NULL THEN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='audit_events_dev_order_fk') THEN
            ALTER TABLE ops.audit_events
            ADD CONSTRAINT audit_events_dev_order_fk
            FOREIGN KEY (dev_order_id) REFERENCES dev.dev_order(dev_order_id)
            ON DELETE SET NULL;
        END IF;
    END IF;

    IF to_regclass('dev.dev_task') IS NOT NULL THEN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='audit_events_dev_task_fk') THEN
            ALTER TABLE ops.audit_events
            ADD CONSTRAINT audit_events_dev_task_fk
            FOREIGN KEY (dev_task_id) REFERENCES dev.dev_task(id)
            ON DELETE SET NULL;
        END IF;
    END IF;
END$$;

COMMIT;
