-- FoxProFlow • FixPack • P0 DevOrders unblock: dev.dev_order + dev.v_dev_order_commercial_ctx (minimal)
-- file: scripts/sql/fixpacks/20251224_dev_order_min_apply.sql
--
-- Goal:
--   - Create dev.dev_order table required by /api/devorders
--   - Create dev.v_dev_order_commercial_ctx view expected by API
--   - Keep CRM/Billing fields as NULL placeholders (typed)
--
-- Idempotent: safe re-run.
-- No DROP. Minimal locks.

\set ON_ERROR_STOP on
\pset pager off

SET lock_timeout = '10s';
SET statement_timeout = '15min';
SET client_min_messages = warning;

SELECT pg_advisory_lock(74858430);

-- Ensure schema exists
CREATE SCHEMA IF NOT EXISTS dev;

-- Ensure UUID generator exists (best-effort)
DO $$
BEGIN
  BEGIN
    EXECUTE 'CREATE EXTENSION IF NOT EXISTS pgcrypto';
  EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'pgcrypto create skipped: %', SQLERRM;
  END;
END $$;

-- Table: dev.dev_order (minimal contract for API insert)
CREATE TABLE IF NOT EXISTS dev.dev_order (
  dev_order_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dev_order_public_id        UUID   NOT NULL DEFAULT gen_random_uuid(),

  title                      TEXT   NOT NULL,
  description                TEXT   NULL,
  customer_name              TEXT   NULL,
  order_tenant_external_id   TEXT   NULL,
  tenant_id                  TEXT   NULL,

  total_amount               NUMERIC NULL,
  currency_code              TEXT    NULL,
  status                     TEXT    NOT NULL DEFAULT 'new',

  created_at                 TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at                 TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Unique constraint on public id (idempotent via DO check)
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint c
    JOIN pg_class t ON t.oid = c.conrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE n.nspname='dev'
      AND t.relname='dev_order'
      AND c.contype='u'
      AND c.conname='dev_order_public_id_uq'
  ) THEN
    EXECUTE 'ALTER TABLE dev.dev_order ADD CONSTRAINT dev_order_public_id_uq UNIQUE (dev_order_public_id)';
  END IF;
END $$;

-- Helpful index for API reads (optional but cheap)
CREATE INDEX IF NOT EXISTS ix_dev_order_created_at ON dev.dev_order (created_at DESC);
CREATE INDEX IF NOT EXISTS ix_dev_order_status     ON dev.dev_order (status);

-- updated_at trigger (idempotent)
CREATE OR REPLACE FUNCTION dev.ff_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger tr
    JOIN pg_class t ON t.oid = tr.tgrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE n.nspname='dev'
      AND t.relname='dev_order'
      AND tr.tgname='trg_dev_order_set_updated_at'
  ) THEN
    EXECUTE '
      CREATE TRIGGER trg_dev_order_set_updated_at
      BEFORE UPDATE ON dev.dev_order
      FOR EACH ROW
      EXECUTE FUNCTION dev.ff_set_updated_at()
    ';
  END IF;
END $$;

-- View: dev.v_dev_order_commercial_ctx (minimal, CRM/Billing placeholders)
CREATE OR REPLACE VIEW dev.v_dev_order_commercial_ctx AS
SELECT
  o.dev_order_id                                        AS dev_order_id,
  o.dev_order_public_id                                 AS dev_order_public_id,

  o.title                                               AS order_title,
  o.description                                         AS order_description,
  o.customer_name                                       AS customer_name,
  o.order_tenant_external_id                            AS order_tenant_external_id,

  o.total_amount                                        AS total_amount,
  o.currency_code                                       AS currency_code,
  o.status                                              AS order_status,
  o.created_at                                          AS order_created_at,
  o.updated_at                                          AS order_updated_at,

  NULL::text                                            AS crm_tenant_table,
  NULL::bigint                                          AS crm_tenant_id,

  NULL::text                                            AS billing_subscription_table,
  NULL::bigint                                          AS billing_subscription_id,

  NULL::text                                            AS billing_invoice_table,
  NULL::bigint                                          AS billing_invoice_id,

  NULL::text                                            AS crm_lead_code
FROM dev.dev_order o;

COMMENT ON TABLE dev.dev_order IS 'DevFactory commercial order (minimal). Created by fixpack 20251224_dev_order_min_apply.sql';
COMMENT ON VIEW dev.v_dev_order_commercial_ctx IS 'Commercial context for dev_order (minimal placeholders for CRM/Billing).';

SELECT pg_advisory_unlock(74858430);

RESET client_min_messages;
RESET statement_timeout;
RESET lock_timeout;
