-- Fixpack: M0 DevFactory DB Contract (idempotent, NDC-safe)
-- Created by: Архитектор Яцков Евгений Анатольевич
-- Purpose:
--   - Ensure dev schema exists
--   - Ensure dev.dev_order exists with INSERT-contract columns used by DevOrders API
--   - Ensure dev.v_dev_order_commercial_ctx exists (NDC-safe: create-if-missing)
--   - Ensure dev.dev_task(public_id) uniqueness (only if table+column exist)
-- Rollback:
--   - NDC: no destructive drops here; rollback is "stop using new objects".
--   - If strict rollback required: write a compensating fixpack (drops view/table) ONLY after verifying no dependencies.

BEGIN;

-- gen_random_uuid() dependency (used across the project)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS dev;

-- 1) dev.dev_order: create if missing
CREATE TABLE IF NOT EXISTS dev.dev_order (
    dev_order_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dev_order_public_id      UUID DEFAULT gen_random_uuid(),
    title                    TEXT,
    description              TEXT,
    customer_name            TEXT,
    order_tenant_external_id TEXT,
    tenant_id                TEXT,
    total_amount             NUMERIC,
    currency_code            TEXT,
    status                   TEXT NOT NULL DEFAULT 'new',
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 2) If table existed but missing columns: add (NDC)
ALTER TABLE dev.dev_order ADD COLUMN IF NOT EXISTS dev_order_public_id      UUID;
ALTER TABLE dev.dev_order ADD COLUMN IF NOT EXISTS title                    TEXT;
ALTER TABLE dev.dev_order ADD COLUMN IF NOT EXISTS description              TEXT;
ALTER TABLE dev.dev_order ADD COLUMN IF NOT EXISTS customer_name            TEXT;
ALTER TABLE dev.dev_order ADD COLUMN IF NOT EXISTS order_tenant_external_id TEXT;
ALTER TABLE dev.dev_order ADD COLUMN IF NOT EXISTS tenant_id                TEXT;
ALTER TABLE dev.dev_order ADD COLUMN IF NOT EXISTS total_amount             NUMERIC;
ALTER TABLE dev.dev_order ADD COLUMN IF NOT EXISTS currency_code            TEXT;
ALTER TABLE dev.dev_order ADD COLUMN IF NOT EXISTS status                   TEXT;
ALTER TABLE dev.dev_order ADD COLUMN IF NOT EXISTS created_at               TIMESTAMPTZ;
ALTER TABLE dev.dev_order ADD COLUMN IF NOT EXISTS updated_at               TIMESTAMPTZ;

-- 3) Enforce types & defaults safely (contract hard checks)
DO $$
DECLARE
    t_public_id text;
BEGIN
    SELECT c.udt_name INTO t_public_id
    FROM information_schema.columns c
    WHERE c.table_schema='dev' AND c.table_name='dev_order' AND c.column_name='dev_order_public_id';

    IF t_public_id IS NULL THEN
        RAISE EXCEPTION 'M0 FIXPACK FAIL: dev.dev_order.dev_order_public_id is missing';
    END IF;

    IF t_public_id <> 'uuid' THEN
        RAISE EXCEPTION 'M0 FIXPACK FAIL: dev.dev_order.dev_order_public_id must be uuid, got %', t_public_id;
    END IF;
END$$;

-- Ensure defaults
ALTER TABLE dev.dev_order ALTER COLUMN dev_order_public_id SET DEFAULT gen_random_uuid();
ALTER TABLE dev.dev_order ALTER COLUMN created_at          SET DEFAULT now();
ALTER TABLE dev.dev_order ALTER COLUMN updated_at          SET DEFAULT now();
ALTER TABLE dev.dev_order ALTER COLUMN status              SET DEFAULT 'new';

-- Backfill NULLs (safe)
UPDATE dev.dev_order SET dev_order_public_id = gen_random_uuid() WHERE dev_order_public_id IS NULL;
UPDATE dev.dev_order SET created_at = now()                     WHERE created_at IS NULL;
UPDATE dev.dev_order SET updated_at = now()                     WHERE updated_at IS NULL;
UPDATE dev.dev_order SET status = 'new'                         WHERE status IS NULL OR btrim(status) = '';

-- Enforce NOT NULL (minimal invariants)
ALTER TABLE dev.dev_order ALTER COLUMN dev_order_public_id SET NOT NULL;
ALTER TABLE dev.dev_order ALTER COLUMN created_at          SET NOT NULL;
ALTER TABLE dev.dev_order ALTER COLUMN updated_at          SET NOT NULL;
ALTER TABLE dev.dev_order ALTER COLUMN status              SET NOT NULL;

-- Optional: minimal “не пустой статус”
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname='dev_order_status_nonempty_ck'
          AND conrelid='dev.dev_order'::regclass
    ) THEN
        ALTER TABLE dev.dev_order
        ADD CONSTRAINT dev_order_status_nonempty_ck CHECK (btrim(status) <> '');
    END IF;
END$$;

-- 4) Unique index on public id (stable name) + clearer failure if duplicates exist
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM (
            SELECT dev_order_public_id
            FROM dev.dev_order
            GROUP BY dev_order_public_id
            HAVING count(*) > 1
        ) d
    ) THEN
        RAISE EXCEPTION 'M0 FIXPACK FAIL: dev.dev_order has duplicate dev_order_public_id values';
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_indexes
        WHERE schemaname='dev' AND indexname='dev_order_public_id_uidx'
    ) THEN
        CREATE UNIQUE INDEX dev_order_public_id_uidx
            ON dev.dev_order (dev_order_public_id);
    END IF;
END$$;

-- 5) updated_at auto-maintenance (safe, idempotent)
CREATE OR REPLACE FUNCTION dev.trg_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_trigger
        WHERE tgname = 'dev_order_set_updated_at'
          AND tgrelid = 'dev.dev_order'::regclass
    ) THEN
        CREATE TRIGGER dev_order_set_updated_at
        BEFORE UPDATE ON dev.dev_order
        FOR EACH ROW
        EXECUTE FUNCTION dev.trg_set_updated_at();
    END IF;
END$$;

-- 6) DevTask public_id uniqueness (only if table+column exist)
DO $$
BEGIN
    IF to_regclass('dev.dev_task') IS NOT NULL THEN
        IF EXISTS (
            SELECT 1
            FROM information_schema.columns c
            WHERE c.table_schema='dev' AND c.table_name='dev_task' AND c.column_name='public_id'
        ) THEN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_indexes
                WHERE schemaname='dev' AND indexname='dev_task_public_id_uidx'
            ) THEN
                CREATE UNIQUE INDEX dev_task_public_id_uidx
                    ON dev.dev_task (public_id)
                    WHERE public_id IS NOT NULL;
            END IF;
        END IF;
    END IF;
END$$;

-- 7) View contract for commercial context (NDC-safe)
-- Important: do NOT CREATE OR REPLACE if view exists (it may have older/wider column contract).
DO $$
BEGIN
    IF to_regclass('dev.v_dev_order_commercial_ctx') IS NULL THEN
        EXECUTE $v$
            CREATE VIEW dev.v_dev_order_commercial_ctx AS
            SELECT
                o.dev_order_id,
                o.dev_order_public_id,
                o.title       AS order_title,
                o.description AS order_description,
                o.customer_name,
                o.order_tenant_external_id,
                o.tenant_id,
                o.total_amount,
                o.currency_code,
                o.status      AS order_status,
                o.created_at  AS order_created_at,
                o.updated_at  AS order_updated_at,

                -- Placeholders for CRM/Billing joins (M0 контракт допускает NULL)
                NULL::text AS crm_tenant_table,
                NULL::text AS crm_tenant_id,
                NULL::text AS billing_subscription_table,
                NULL::text AS billing_subscription_id,
                NULL::text AS billing_invoice_table,
                NULL::text AS billing_invoice_id,
                NULL::text AS crm_lead_code
            FROM dev.dev_order o
        $v$;
    END IF;
END$$;

COMMIT;
