-- Fixpack: M0 CRM DB Contract (idempotent, NDC-safe)
-- Created by: Архитектор Яцков Евгений Анатольевич
-- Purpose:
--   - Ensure crm schema exists
--   - Ensure crm.tenants(id uuid default ...) exists + timestamps invariants
--   - Ensure crm.leads minimal columns exist (as used by CRM smoke v2) + invariants
--   - Ensure crm.leads_trial_candidates_v is queryable (NDC-safe: create-if-missing; self-heal if broken and no dependents)
-- Rollback:
--   - NDC: no destructive drops here by default; rollback is "stop using".
--   - If strict rollback required: compensating fixpack only after dependency check.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS crm;

-- 1) crm.tenants (minimal contract)
CREATE TABLE IF NOT EXISTS crm.tenants (
    id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name       TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Hard contract checks (fail fast if types incompatible)
DO $$
DECLARE
    t_id text;
BEGIN
    SELECT c.udt_name INTO t_id
    FROM information_schema.columns c
    WHERE c.table_schema='crm' AND c.table_name='tenants' AND c.column_name='id';

    IF t_id IS NULL THEN
        RAISE EXCEPTION 'M0 FIXPACK FAIL: crm.tenants.id is missing';
    END IF;

    IF t_id <> 'uuid' THEN
        RAISE EXCEPTION 'M0 FIXPACK FAIL: crm.tenants.id must be uuid, got %', t_id;
    END IF;
END$$;

-- Ensure id default exists (if table existed)
ALTER TABLE crm.tenants ALTER COLUMN id SET DEFAULT gen_random_uuid();

-- Ensure timestamps defaults + NOT NULL (safe backfill)
ALTER TABLE crm.tenants ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
ALTER TABLE crm.tenants ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE crm.tenants ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE crm.tenants ALTER COLUMN updated_at SET DEFAULT now();

UPDATE crm.tenants SET created_at = now() WHERE created_at IS NULL;
UPDATE crm.tenants SET updated_at = now() WHERE updated_at IS NULL;

ALTER TABLE crm.tenants ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE crm.tenants ALTER COLUMN updated_at SET NOT NULL;

-- 2) crm.leads (minimal contract)
CREATE TABLE IF NOT EXISTS crm.leads (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    UUID NULL,
    source       TEXT,
    status       TEXT NOT NULL DEFAULT 'new',
    company_name TEXT,
    contact_name TEXT,
    email        TEXT,
    phone        TEXT,
    country      TEXT,
    region       TEXT,
    payload      JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Add missing columns if leads existed (NDC)
ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS tenant_id    UUID;
ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS source       TEXT;
ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS status       TEXT;
ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS company_name TEXT;
ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS contact_name TEXT;
ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS email        TEXT;
ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS phone        TEXT;
ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS country      TEXT;
ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS region       TEXT;
ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS payload      JSONB;
ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS created_at   TIMESTAMPTZ;
ALTER TABLE crm.leads ADD COLUMN IF NOT EXISTS updated_at   TIMESTAMPTZ;

-- Hard contract checks for leads (types)
DO $$
DECLARE
    t_tenant_id text;
BEGIN
    SELECT c.udt_name INTO t_tenant_id
    FROM information_schema.columns c
    WHERE c.table_schema='crm' AND c.table_name='leads' AND c.column_name='tenant_id';

    IF t_tenant_id IS NULL THEN
        RAISE EXCEPTION 'M0 FIXPACK FAIL: crm.leads.tenant_id is missing';
    END IF;

    IF t_tenant_id <> 'uuid' THEN
        RAISE EXCEPTION 'M0 FIXPACK FAIL: crm.leads.tenant_id must be uuid, got %', t_tenant_id;
    END IF;
END$$;

-- Enforce defaults + NOT NULL for payload/created_at/updated_at + status (safe backfill)
ALTER TABLE crm.leads ALTER COLUMN payload    SET DEFAULT '{}'::jsonb;
UPDATE crm.leads SET payload = '{}'::jsonb WHERE payload IS NULL;
ALTER TABLE crm.leads ALTER COLUMN payload    SET NOT NULL;

ALTER TABLE crm.leads ALTER COLUMN created_at SET DEFAULT now();
ALTER TABLE crm.leads ALTER COLUMN updated_at SET DEFAULT now();
UPDATE crm.leads SET created_at = now() WHERE created_at IS NULL;
UPDATE crm.leads SET updated_at = now() WHERE updated_at IS NULL;
ALTER TABLE crm.leads ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE crm.leads ALTER COLUMN updated_at SET NOT NULL;

ALTER TABLE crm.leads ALTER COLUMN status SET DEFAULT 'new';
UPDATE crm.leads SET status = 'new' WHERE status IS NULL OR btrim(status) = '';
ALTER TABLE crm.leads ALTER COLUMN status SET NOT NULL;

-- Minimal invariant: status must be non-empty
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname='crm_leads_status_nonempty_ck'
          AND conrelid='crm.leads'::regclass
    ) THEN
        ALTER TABLE crm.leads
        ADD CONSTRAINT crm_leads_status_nonempty_ck CHECK (btrim(status) <> '');
    END IF;
END$$;

-- Optional FK (safe add, stable name)
DO $$
BEGIN
    IF to_regclass('crm.tenants') IS NOT NULL THEN
        IF NOT EXISTS (
            SELECT 1 FROM pg_constraint
            WHERE conname='crm_leads_tenant_fk'
              AND conrelid='crm.leads'::regclass
        ) THEN
            ALTER TABLE crm.leads
            ADD CONSTRAINT crm_leads_tenant_fk
            FOREIGN KEY (tenant_id) REFERENCES crm.tenants(id)
            ON DELETE SET NULL;
        END IF;
    END IF;
END$$;

-- Helpful indexes (lightweight)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='crm' AND indexname='crm_leads_status_idx') THEN
        CREATE INDEX crm_leads_status_idx ON crm.leads (status);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_indexes WHERE schemaname='crm' AND indexname='crm_leads_tenant_id_idx') THEN
        CREATE INDEX crm_leads_tenant_id_idx ON crm.leads (tenant_id) WHERE tenant_id IS NOT NULL;
    END IF;
END$$;

-- updated_at auto-maintenance (safe, idempotent)
CREATE OR REPLACE FUNCTION crm.trg_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at := now();
    RETURN NEW;
END;
$$;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname='crm_tenants_set_updated_at'
          AND tgrelid='crm.tenants'::regclass
    ) THEN
        CREATE TRIGGER crm_tenants_set_updated_at
        BEFORE UPDATE ON crm.tenants
        FOR EACH ROW
        EXECUTE FUNCTION crm.trg_set_updated_at();
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_trigger
        WHERE tgname='crm_leads_set_updated_at'
          AND tgrelid='crm.leads'::regclass
    ) THEN
        CREATE TRIGGER crm_leads_set_updated_at
        BEFORE UPDATE ON crm.leads
        FOR EACH ROW
        EXECUTE FUNCTION crm.trg_set_updated_at();
    END IF;
END$$;

-- 3) View must be queryable (smoke does COUNT(*))
-- NDC-safe strategy:
--   - If missing: CREATE VIEW
--   - If exists: validate it's queryable
--     - If broken: try DROP VIEW (no CASCADE). If dependents exist -> fail with clear message.
DO $$
BEGIN
    IF to_regclass('crm.leads_trial_candidates_v') IS NULL THEN
        EXECUTE $v$
            CREATE VIEW crm.leads_trial_candidates_v AS
            SELECT l.*
            FROM crm.leads l
            WHERE l.status IN ('new','trial','qualified')
        $v$;
    ELSE
        BEGIN
            -- validate it compiles & runs
            EXECUTE 'SELECT 1 FROM crm.leads_trial_candidates_v LIMIT 1';
        EXCEPTION WHEN others THEN
            BEGIN
                EXECUTE 'DROP VIEW crm.leads_trial_candidates_v';
            EXCEPTION WHEN dependent_objects_still_exist THEN
                RAISE EXCEPTION
                    'M0 FIXPACK FAIL: crm.leads_trial_candidates_v exists but is broken and has dependents. Manual NDC required (create v2 + switch consumers + drop old).';
            END;

            EXECUTE $v$
                CREATE VIEW crm.leads_trial_candidates_v AS
                SELECT l.*
                FROM crm.leads l
                WHERE l.status IN ('new','trial','qualified')
            $v$;
        END;
    END IF;
END$$;

COMMIT;
